version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: ci/server.Dockerfile
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: '8888'
    ports:
      - '8888:8888'
    restart: on-failure
    healthcheck:
      test: 'netstat -ltn | grep -c 8888 || exit 1'
      interval: 1s
      timeout: 5s
      retries: 120


  client:
    build:
      context: .
      dockerfile: ci/client.Dockerfile
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: '8888'
    restart: on-failure
    depends_on:
     - server
